### ISSUE TITLE
Consistent Searching Functionality

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#101]
**Is your feature request related to a problem? Please describe.**
Some of our users are complaining about the inconsistent search functionality across the service. I'll explain.
##### Dashboard - Apps Section
Searching by name only shows results if the entire string matches the entire name of the app. We'd expect substrings to show results for apps e.g. searching for "sol" would include "Solitaire" in the results. 
This wasn't as much of a problem previously but we have enough apps that the Apps section is paginated so more users are searching for their app rather than browsing for it.

##### Dashboard - People Section
Searching for email under Collaborators is currently giving an error:
> The information sent is not valid

Also, similar to the Apps Section, the results will only show exact matches for searches, substrings don't give positive results.

##### Store Site
Many of our users are confused when they search on the store site. The results seem to be generated based on if the app name contains any character in any order from the search term (searching for "slot" gives the result "Solitaire". There is also seemingly some probability taken into account in the results where not all characters need to be included for a result to show up (searching for "solzzz" still gives the result for "Solitaire")

**Describe the solution you'd like**
We'd like all search results to be based on substring searching (a item named '123abc456def' would be shown when searching for either 'abc' or '456' but not 'cba' or '2ab') 

As always, we appreciate the effort you put into our requests!

**Comment by CesarTrigo** [comment]
Hi @mkm12789,

Please find below some updates:
- Dashboard - Apps Section - Searching by name (substrings): fixed ✅ & deployed 🚀
- Dashboard - People Section - Searching by email (error): fixed ✅ & deployed 🚀
- Dashboard - People Section - Searching by email (substrings): fixed ✅ & deployed 🚀

Regarding the **App Store**, we will need to invest some additional time to find the best solution since we are using an AI powered library that provides automatic prediction and tries to minimize common writing mistakes. I'll come back to you once we find a solution.

As always, thank you for the continuous feedback!

**Comment by CesarTrigo** [comment]
Hi @mkm12789
We have just released a new version of the App Store that solves this situations mentioned above. Now, searching for "solzzz" provides no results but it works if you search for "sol" and only retrieves Distributions that contain "Solitaire" results.
I would suggest you to play around a bit with it and reopen the issue if you still think it is not working as expected.

**As a summary:**
- Dashboard - Apps Section - Searching by name (substrings): fixed ✅ & deployed 🚀
- Dashboard - People Section - Searching by email (error): fixed ✅ & deployed 🚀
- Dashboard - People Section - Searching by email (substrings): fixed ✅ & deployed 🚀
- Store - Searching by App Name: fixed ✅ & deployed 🚀

As usual, thank you for the great feedback!

C.
