### ISSUE TITLE
Increase 'Shareability' of builds from Dashboard

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#102]
**Describe the solution you'd like**
Some teams in our company have a need to link directly to older builds. The only way to do this is using the Dashboard by selecting the build and copying the URL.
We'd like an option to share a link to directly download the build.

1. I've received suggestions to add an actual "share" button next to the "Download" button on the build's details view pane.
2. Others would like a QR code somewhere on the build's details view pane as well.

Both options would give a link to immediately start download/install of the build.

As always, we appreciate the effort you put into our requests!

**Comment by CesarTrigo** [comment]
Hi @mkm12789,

Thank you for reaching us with new ideas!

Just to confirm our understanding, you would like to have this feature in the Dashboard so Collaborators can directly jump into a Build and start the installation if they are navigating from their mobile phone devices.

Is that correct?

Thank you,
C.

**Comment by mkm12789** [comment]
Correct. One use case, for example, is Collaborators sending an email asking other Collaborators to download an old build. They would like to include a link for mobile users to click and start installing (obviously if they'd have to login if necessary)

**Comment by CesarTrigo** [comment]
Great @mkm12789 , thank you for confirming. 
Build already have a permalink that allows you to jump directly into the build details that already allows users to install the build:
`https://dashboard.applivery.io/{org}/apps/{app_slug}/builds?id={build_id}`

However, I think we should implement the following improvements:
- Put a **Share button** that:
  - Allows the user to Automatically copy the permalink into the clipboard.
  - Provides a QR code that points to that permalink
- Switch the "Download" button label to "Install" when browsing over a Mobile Phone.

Your feedback will be welcome! Moving to Selected for Development.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 ,
This issue has been resolved and deployed a few minutes ago including both the auto-copy & paste of link and the QR Code (please make sure to refresh the cache of the browser).

<img width="680" alt="share" src="https://user-images.githubusercontent.com/453657/80820475-37494680-8bd7-11ea-80d6-2749d4f32993.png">

**Comment by CesarTrigo** [comment]
Dear @mkm12789,
I just want to let you know that this option will be available soon also in the App Store for both Apps and builds (#138)
Best,
C.
