### ISSUE TITLE
Return full App Store Distribution URL for POST and GET /integrations/distributions API methods

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#103]
**Describe the solution you'd like**
Return App Store Distribution URL (including for Custom Domains)

**Describe alternatives you've considered**
Nowadays, users have to compose the URL manually as follows: `customdomain.applivery.io/{distribution_slug}`

**Requested by:** @RafaelFernandezAlv

**Comment by CesarTrigo** [comment]
Hi @RafaelFernandezAlv,
A new parameter called `distributionUrl` that will return full Distribution Site URL has been included in the following methods:
- `POST`: [Create New Distribution Site](https://www.applivery.com/docs/api/create-distribution-site/)
- `GET`: [Get list of Distribution Sites](https://www.applivery.com/docs/api/get-list-distribution-sites/)
- `GET`: [Get distribution Site Details](https://www.applivery.com/docs/api/get-distribution-site-details/)

Hope you find it useful.
C.

**Comment by RafaelFernandezAlv** [comment]
Hi, thanks for add the new parameter. I saw that the new parameter in the documentation return the full url of App Store Distribution URL (even the `https` protocol) but in my case not. Is this a bug?

**Comment by CesarTrigo** [comment]
Hi @RafaelFernandezAlv 
Thank you for raising that point. It will be available throughout the day.
I'll keep you posted.
C.

**Comment by CesarTrigo** [comment]
Hi @RafaelFernandezAlv,
It should be fixed now and you should start getting the protocol along with the full URL.
Regards,
C.

**Comment by RafaelFernandezAlv** [comment]
Thanks! Now It works
