### ISSUE TITLE
New employees invitations are not leading users to setting a password

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#106]
**Describe the bug**
New employees invited to Private App Stores should set a password before accessing the Store.

**To Reproduce**
1. Go to your Organization
2. Invite a new Employee
3. Employee receives an email
4. Employee is lead directly to the login page instead to the set password form.

**Expected behavior**
Employees should set a password before they can login so they should go to the set password form.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Reported by: ** @RafaelFernandezAlv

**Comment by CesarTrigo** [comment]
Hi @RafaelFernandezAlv,
A fix has been deployed and it should now lead users to the "Set password" form before accessing the App Store if it has been configured as Private.
Apologies for the inconvenience and thanks for the report.
C.

**Comment by RafaelFernandezAlv** [comment]
Thanks! It's working
