### ISSUE TITLE
App Store list of Apps not displaying the appropriate App icon for Tag type of distributions

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#110]
**Describe the bug**
When publishing a new distribution based on a given `tag`, the icon displayed in the list of Apps of the App Store is the last one available for that App (independently of the `tag`), not the last one of that `tag`.

Most probably that's also happening for the rest of the types of distributions.

**To Reproduce**
1. Create a new publication by tag
2. Create a new publication by last
2. Upload a new build that is not associated to that tag (so the main icon of the App changes)
3. Go to the Store and see that both will be displayed using the last build uploaded icon

**Expected behavior**
The `tag` distribution should show the icon of the last build that matches that `tag`

**Screenshots**
![screenshot-2020-02-14-at-09462_d54w05](https://user-images.githubusercontent.com/453657/74526032-cae97000-4f22-11ea-9d97-5076427609ea.png)
![screenshot-2020-02-14-at-09463_1raz59p](https://user-images.githubusercontent.com/453657/74526029-ca50d980-4f22-11ea-8e30-70d61489586f.png)

Reported by: @RafaelFernandezAlv

**Comment by CesarTrigo** [comment]
Fixed and ready to be deployed this week along with some other small fixes.

**Comment by RafaelFernandezAlv** [comment]
Is this already uploaded? For the history of the app I see the correct icon but not for the current app
![Screenshot 2020-02-24 at 07 46 31](https://user-images.githubusercontent.com/1234765/75133133-e0585a00-56d9-11ea-8806-e740fc768797.png)

**Comment by CesarTrigo** [comment]
Hi @RafaelFernandezAlv, thank you for the follow up.
As you have noticed, this is only partially fixed and there are additional frontend improvements waiting to be released this week that will provide a complete solution.
I'll notify you once done.
C.

**Comment by CesarTrigo** [comment]
@RafaelFernandezAlv it has been fixed and released

**Comment by RafaelFernandezAlv** [comment]
Thanks!
