### ISSUE TITLE
Store Page Build Link to “View in Dashboard” for Collaborators

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#113]
**Is your feature request related to a problem? Please describe.**
Occasionally some of our developers (who are Collaborators) need to view more details about a build in the Dashboard that they’re viewing in a Store Page. They have to navigate to the dashboard, then go to their app’s builds, and search for the build they want to look at.

**Describe the solution you'd like**
To reduce friction, we’d like some kind of a link or button in the builds views of Store Pages (including under the History tab) to “View this build in the Dashboard”. Obviously, the link or button would only be visible to Collaborators or at least greyed-out for Employees.

**Comment by CesarTrigo** [comment]
Hi @mkm12789,
Thank you for opening this Feature Request. We will review it and come back to you.
Regards,
C.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 
This feature has been deployed today along with other minor updates. All collaborators navigating through the App Store will now see:
* The `View in Dashboard` link at the very bottom of the App details that will lead to the last build details (the default one for the current Distribution)
* A small share icon to jump to the Build details on every build
Below you can find some evidences:
![app](https://user-images.githubusercontent.com/453657/80918908-98a01f80-8d67-11ea-8256-64982f04baa7.PNG)
![build](https://user-images.githubusercontent.com/453657/80918912-9a69e300-8d67-11ea-8550-2e75b27d68e5.PNG)


Hope you find them useful.
C.

**Comment by mkm12789** [comment]
Hey @CesarTrigo it looks like there may be a bug in this feature. The generated URL uses the slug name instead of the app name to generate the dashboard URL.
Example:

This returns a 404:
https://dashboard.applivery.io/[orgname]/apps/solitaire-dev-d-google/builds?id=[buildid]

This is what the URL should be
https://dashboard.applivery.io/[orgname]/apps/solitaire/builds?id=[buildid]

Where "solitaire-dev-d-google" is the slug of the store page I was viewing before clicking VIEW IN DASHBOARD

**Comment by CesarTrigo** [comment]
Thank you @mkm12789.
Reopening and under investigation.

**Comment by CesarTrigo** [comment]
Hi @mkm12789. This should work as expected now.
Thank you,
C,
