### ISSUE TITLE
Desktop Download from Store Page

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#114]
**Is your feature request related to a problem? Please describe.**
We want to add our 3rd party QA team to our organization. Naturally we'd like to add them as "Employees". There's a special need for this QA team though as they need to be able to re-sign AdHoc iOS builds to work on their devices. Using a different service they're able to download our builds to their desktops, re-sign, then distribute amongst themselves. The Applivery Store doesn't let users download to their desktops so the only way for them to download the builds would be to set them up as "Collaborators" which is more access we want to give.

**Describe the solution you'd like**
The ability to download apps from the Applivery Store pages when browsing on a desktop.

**Describe alternatives you've considered**
We might have to add the 3rd party QA as Collaborators to just the apps we want them to have access to but it would add a lot of work to manage every user in each of the apps we want them to test.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 thank you for opening this topic.
We will check it internally and come back to you.

Regards,
C.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 this issue will most probably not be implemented since it is already covered by #113  and #102 FRs. Additionally we consider insecure providing `IPA's` and `APK's` files from a place that cloud be totally public.
