### ISSUE TITLE
Download AAB Option

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#120]
**Is your feature request related to a problem? Please describe.**
We'd like to host our AABs in Applivery and the recent feature that was released is a great help for us. When it comes time for us to submit apps to the Play Store we'd like to use those same AABs that are in Applivery.

**Describe the solution you'd like**
We would like an option to download AABs from Applivery.

**Describe alternatives you've considered**
We're currently self-hosting our AABs to use for app submissions

**Comment by CesarTrigo** [comment]
Hi @mkm12789 the issue has been resolved and released a few minutes ago. You can find the "Download .aab file" option below of the Share & Download buttons for APKs that were generated from a `.aab` file.

Thank you once more for the feedback!
<img width="679" alt="aab" src="https://user-images.githubusercontent.com/453657/80820662-9ad37400-8bd7-11ea-97d7-96437a355d55.png">
