### ISSUE TITLE
Include latest build in History tab on Store Sites

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#125]
**Is your feature request related to a problem? Please describe.**
A few of our users have been confused when viewing the History tab on a Store Site in Applivery. They assume the history tab shows the full history including the latest build but that build is only under the details section

**Describe the solution you'd like**
Include the latest build under the History tab.

This is a low priority request

**Comment by CesarTrigo** [comment]
Done and released. Example:
<img width="360" alt="latest" src="https://user-images.githubusercontent.com/453657/81572135-1fc24880-93a3-11ea-818c-f37a9b964dcf.png">
