### ISSUE TITLE
Conditionally disable installation of iPad only Builds for other iOS devices

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#130]
**Is your feature request related to a problem? Please describe.**
Sometimes users are uploading iPad only Apps that are not compatible with other iOS devices (such as iPod or iPhone).

**Describe the solution you'd like**
App Store should be able to identify those iPad only Builds and exclude (or disable installation) if the visitor is running on an iPhone or iPod device.

Cc: @RafaelFernandezAlv

**Comment by CesarTrigo** [comment]
Postponed to Q3-Q4.

**Comment by burak-pensa** [comment]
A kindly reminder for @CesarTrigo.

**Comment by CesarTrigo** [comment]
Dear @burak-pensa 
This feature has been finally resolved and deployed in production. May I ask you to give it a try?
Apologies for the big delay on resolving this request.
C.

**Comment by burak-pensa** [comment]
Hi @CesarTrigo, 
A big thank you to the Applivery team for their efforts. The feature works like a charm. :)
