### ISSUE TITLE
Applivery not retaining IPA file names

### ISSUE THREAD

**Issue by mw-gbhor** [applivery/roadmap#132]
**Describe the bug**
iOS IPA files uploaded with specific names are being served for download with a random string as the file name. This does not happen for Android APK files.

**To Reproduce**
1. Create an IPA file and name it **app_production_1.1.0.ipa**
2. Login to the dashboard and go to your app
3. Upload the IPA file and wait for it to be processed
4. Click the download button and the resulting downloaded file will have a random string for the file name.

**Expected behavior**
Downloaded IPA file should retain the file name which was used when uploading it.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version 81.0.4044.129 (Official Build)

**Comment by CesarTrigo** [comment]
Hi @mw-gbhor 
Thank you for contacting us. The team is already looking into this.
We will come back to you ASAP.
Regards,
C.

**Comment by CesarTrigo** [comment]
Hi @mw-gbhor,
It's under QA and will be deployed soon.
Best,
C.

**Comment by CesarTrigo** [comment]
Hi @mw-gbhor! It has been released!

**Comment by mw-gbhor** [comment]
It is working as expected. Thank you @CesarTrigo.
