### ISSUE TITLE
REST API to Patch Distribution Sites

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#133]
**Is your feature request related to a problem? Please describe.**
As we continue to grow our usage of Applivery in the company, there have been many requests for updating group policies for our 3rd party "Employee" users. Currently I have to manually add/change the individual group settings for each distribution site.

**Describe the solution you'd like**
I would like a way to programatically update the groups for a distribution site. A "Patch" API call would be perfect this use case.

**Comment by CesarTrigo** [comment]
Hi @mkm12789, thank you! This is being considered.

Right now there's a public method under the [Organizations API](https://www.applivery.com/docs/api/spec/main/#tag/Store-Published-Applications/paths/~1organizations~1:organizationId~1stores~1:storeId~1publishedApplications~1:publishedApplicationId/put). That API requires a [Service Account](https://www.applivery.com/docs/api/service-accounts/) for authentication so we are considering exposing a new endpoint on the [Apps API](https://www.applivery.com/docs/api/).

I will come back to you with the decision this week.

Best,
C.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 ,
A new endpoint has been included in the documentation (https://www.applivery.com/docs/api/put-edit-a-distribution-site/) to enable the update of the Distribution Sites.
Hope you find it useful.
Best,
C.
