### ISSUE TITLE
Option to include Tags with Slack integration notification

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#134]
**Is your feature request related to a problem? Please describe.**
The 'new build uploaded' Slack integration notification currently includes Org, App, OS, and Build. We upload multiple builds with the same version number that we differentiate with tags.

**Describe the solution you'd like**
We'd like an option to include tags in the Slack notification.
It would also be nice to customize which information is displayed by the Slack notification (we only use one Org so it would be nice to turn that off), but that's not a requirement for this request.

**Comment by CesarTrigo** [comment]
Thank you @mkm12789 ,
We are checking this in detail and will come back to you with the best solution possible.
Regards,
C.

**Comment by CesarTrigo** [comment]
This feature has been finished including all fields in the notification. To be published in the next release.

**Comment by CesarTrigo** [comment]
Hi all! This FR has been released a few minutes ago. New Webhooks now include all CI parameters.
C.
