### ISSUE TITLE
Guest user role in Dashboard

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#136]
Some users are reporting the need of having a new type of user with read access to the dashboard, mainly focused on 3rd party accesses. We are analyzing the creation of new user role called `Viewer`.

**Comment by CesarTrigo** [comment]
Dear @mkm12789, this new feature is ready to be released next week. The new user role is called "Viewer".
Regards,
C.

**Comment by mkm12789** [comment]
Thanks @CesarTrigo for all of the updates!
Is it possible to restrict a 'Viewer' from seeing an App's 'API Auth' tokens from the App's Settings page?
Otherwise this looks to be perfect for our use case.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 we already considered that improvement but it's under development and will be released in the coming days. The entire Settings page for both the Organization and Apps will be totally hidden for Viewers. I will let you know once ready.
Best,
C.
