### ISSUE TITLE
Dashboard 'Search by Tag' Selection and URL Issues

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#140]
**Describe the bug**
_Selection Issue_
On an App's Build page in the Dashboard, when trying to search for a tag, if you use the mouse to select a tag from the filtered suggestions, the populated result is the partial text you typed and some other tag. Using the keyboard and hitting 'Enter' seems to work fine but the mouse has issues. This was produced using Chrome on a Mac.
![tags](https://user-images.githubusercontent.com/1542685/95380589-cf8cdb00-089b-11eb-8080-8b5c3a7179b9.gif)

_URL Issue_
Visiting a URL with a filtered tag POST message, the tags are not searched for separately, but rather as one, comma-separated tag. For example, if you had searched for tags 'test' and 'debug' separately, copied the URL and revisited it, the search results would be for one tag 'test,debug'.
![separate tags](https://user-images.githubusercontent.com/1542685/95380958-5641b800-089c-11eb-9095-58dc7163b09d.png)

![combined tags](https://user-images.githubusercontent.com/1542685/95380921-4c1fb980-089c-11eb-85dc-ab12e468a145.png)

**To Reproduce**
_Selection Issue_
1. Visit and App's Build page.
2. Begin typing the name of a tag.
3. Select the tag from the list with your mouse.

_URL Issue_
1. Visit and App's Build page.
2. Filter the list with multiple tags.
3. Copy the URL and past in a new Browser Tab.

**Expected behavior**
_Selection Issue_
The tag that is clicked on should be populated and only that on should be populated.

_URL Issue_
The page should properly separate the different tags for an OR search instead of single tag search.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 
We have successfully fixed this issue, however we have detected a new one that splits the selected tag in two when selecting it with the mouse. It works as expected when selecting it though the keyboard or when writing the full tag name. The team is working on a fix. In the meantime I will consider this issue as fixed and released.

**Comment by mkm12789** [comment]
Thanks @CesarTrigo! Please let me know when the fix for selection via mouse is available. Is there a separate ticket I can track for that issue?
