### ISSUE TITLE
Slack Integration Enhancements

### ISSUE THREAD

**Issue by stephenconner** [applivery/roadmap#141]
Problem: The slack integration is not customisable.

Solution we would like:
We would like the ability to choose which Applivery fields are included in the call to slack on binary upload.

We tried a custom webhook into slack. Slack requires the json to be formatted in Slack's block kit way or else it cannot parse and fails to trigger the webhook.

**Comment by CesarTrigo** [comment]
Hi @stephenconner thank you for opening this request.
May I ask you to specify which specific fields of the build would you be interested in receiving through the Slack message?

Thank you,
C.

**Comment by stephenconner** [comment]
We set some of all of these when we upload builds, it would be nice to be
able to select which of them are sent back to slack...

"versionName"
"tags"
"deployer.name"
"deployer.info.branch"
"deployer.info.buildNumber"
"deployer.info.buildUrl"
"deployer.info.ciUrl"
"deployer.info.commitMessage"
"deployer.info.commit"
"deployer.info.tag"
"deployer.info.repositoryUrl"

**Comment by mkm12789** [comment]
Related issue
https://github.com/applivery/roadmap/issues/134

**Comment by CesarTrigo** [comment]
This feature has been finished including all fields in the notification. To be published in the next release.

**Comment by CesarTrigo** [comment]
Hi all! This FR has been released a few minutes ago. New Webhooks now include all CI parameters.
C.
