### ISSUE TITLE
Distribution Sites - DELETE API

### ISSUE THREAD

**Issue by mw-gbhor** [applivery/roadmap#147]
**Is your feature request related to a problem? Please describe.**
We manage over 30 apps and each app has over 15 distribution sites. We like and use the Distribution Site APIs to create/update the sites (https://www.applivery.com/docs/api/). However, we aren't able to automate the cleanup or deletion of the distribution sites due to the absence of the DELETE API. This is especially hurting us as we want to run maintenance tasks on our account or when we host Hackathon-like events that require creating many temporary apps and distribution sites.

**Describe the solution you'd like**
Can you please consider adding a DELETE API to the Distribution Sites API Collection? Specifically, the one on this page: https://www.applivery.com/docs/api/. It seems like the Builds and Employees API Collections already have the DELETE API. This seems to be missing from the Distribution Sites API Collection.

**Describe alternatives you've considered**
We did explore the Organization API (https://www.applivery.com/docs/api/spec/main/#tag/Store-Published-Applications) for managing Distribution Sites/Published Apps. However, that API requires an account-level API key which has a lot of power and privileges. We like the Distribution Site APIs more as their scope can be limited by supplying an app-level API key.

Please let me know if you need more information or clarification.

**Comment by CesarTrigo** [comment]
Thank you for opening such a detailed FR @mw-gbhor 
It has been already reviewed and planned for a quick implementation.
Will keep you posted here.
Regards,
C

**Comment by CesarTrigo** [comment]
Dear @mw-gbhor,
I just want to let you know that this request has been successfully developed. It's right now under QA and documentation. I will let you know once released.
Best,
C.

**Comment by CesarTrigo** [comment]
Dear @mw-gbhor 
This new feature has been deployed and is now generally available. You can check the documentation here: https://www.applivery.com/docs/api/delete-distribution-site/

Best regards,
C.
