### ISSUE TITLE
Cert Build Tag is Ad Hoc for App Store Builds

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#149]
**Describe the bug**
In the list of builds on the dashboard, the Applivery-populated Cert tag for iOS builds is showing "Ad Hoc" for builds that are signed with an "App Store" provisioning profile. This has caused some confusion for our teams when trying to differentiate between Ad Hoc and App Store builds.

**To Reproduce**
1. Sign and IPA with an App Store provisioning profile
2. Upload the build to Applivery
3. Notice the Cert Build Tag

**Expected behavior**
The Cert Build Tag should be something like "App Store" or "Mac App Store" to differentiate it as a separate type of profile.

**Screenshots**
Builds with the tag "distribution" in the screenshot below are App Store builds

![Screen Shot 2021-01-26 at 9 10 59 AM](https://user-images.githubusercontent.com/1542685/105879414-00ae2a00-5fb7-11eb-9099-453140488ca7.png)
![Screen Shot 2021-01-26 at 9 15 31 AM](https://user-images.githubusercontent.com/1542685/105879467-0efc4600-5fb7-11eb-83e5-4d1870dde930.png)

**Comment by CesarTrigo** [comment]
Hi @mkm12789 thank you for reporting this issue.
We have categorized it as a High Priority issue so hope to provide feedback by tomorrow the latest.
Thank you,
C.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 we have fixed the issue and the fix is under QA. We hope to release it in the next few days.
C.

**Comment by CesarTrigo** [comment]
Hi @mkm12789 . The issue has been fixed and released and a new "App Store" tag will appear next to these type of builds. Here is an example:
<img width="217" alt="Captura de pantalla 2021-02-02 a las 19 07 57" src="https://user-images.githubusercontent.com/453657/106643474-12c93300-658a-11eb-9e8a-fc540ccfdc97.png">
Please let us know if you find any edge case.
Regards,
C.
