### ISSUE TITLE
User Management Issues

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#151]
**Describe the bug**
After trying some new user management strategies for our Organization, I came across a few bugs that are somewhat related to each other which is why I didn't create multiple Issues:

### Collaborator Count
If the same user is added as a Collaborator to multiple apps, the user is counted multiple times in the overall Collaborators count.

### Organization Role Overrides App
If a user is a Collaborator at the Organization level as well as at an individual App level, the role at the Organization level will override that of the App.
The use case for this is if we have a developer who we want to have Viewer access to all apps but Developer access to a single app.

### Groups Not Respecting App/Org Differences
This one is a minor issue as it can be resolved by better group management on our part. But I did notice an odd situation where if a user is a Collaborator at the Organization level with no group associated to them, and that same user is a Collaborator at the app level with a group associated to them, they have the same viewing permissions as if the group was at the Organization level. This is reproducible with Employees as well. It seems as though anywhere a user has a group associated with them, that user has that group across all access points. 
**Example**
App1 has sites with Group1
App2 has sites with Group1 (same name as the one in App1)
User is Collaborator under Organization without a group
User is added as a Collaborator to App1 with Group1
User can view sites in App2 that have Group1 associated to them

**Comment by CesarTrigo** [comment]
Hi @mkm12789, thank you for all the details you have provided.
We are investigating the 3 scenarios and treat them as separate issues on our side. However we will treat them as a single one here. Will keep you posted.

**Comment by CesarTrigo** [comment]
Dear @mkm12789 ,
- Groups Not Respecting App/Org Differences issue has been fixed and already released
- Organization Role Overrides App has been fixed and will be deployed during next week
- Collaborator Count is also reported in #148, that is "In progress" status.

Closing and waiting for release

**Comment by CesarTrigo** [comment]
After a successful release we can consider all issues here as fixed.
