### ISSUE TITLE
[Feature]: Increase width of "Git branch" field/dropdown in Dashboard

### ISSUE THREAD

**Issue by mw-mmiller** [applivery/roadmap#185]
### Contact details

mmiller@mobilityware.com

### Is your feature request related to a problem or need? Please describe.

Our team uses ticket numbers to name the feature branches that resolve the ticket. When filtering builds by "git branch" the dropdown is not wide enough to easily differentiate between the list of branches (see screenshot)
<img width="129" alt="Screen Shot 2021-09-14 at 4 01 36 PM" src="https://user-images.githubusercontent.com/30912036/133465930-05aa5b43-8ed2-4897-a1c7-555c3609c649.png">

### Describe the solution you'd like

The "Git branch" field and dropdown width to be either dynamic with perhaps a max width in the case of an extremely long branch name, or a hardcoded width that's large than the current. I think 300px would be plenty wide enough for our use case.

### Describe alternatives you've considered

None, as this is more of a quality-of-life improvement. Teams just type out or copy-paste the full name of their branches now.

**Comment by CesarTrigo** [comment]
Thank you for opening this request @mw-mmiller.
We are already considering its prioritization.
Best regards,
C.

**Comment by CesarTrigo** [comment]
Waiting for release

**Comment by CesarTrigo** [comment]
Released today!

**Comment by CesarTrigo** [comment]
Just @mw-mmiller for his information and confirmation that now tags are visible in the drop-downs as expected.
Thank you
C.
