### ISSUE TITLE
[Feature] Ordenación en lista de Devices

### ISSUE THREAD

**Issue by JacobFLRepsol** [applivery/roadmap#191]
### Contact details

jacob.fernandez@repsol.com

### Is your feature request related to a problem or need? Please describe.

Cuando liberamos versión de app o hacemos seguimiento de algún bug sobre una versión de Android, vamos a la lista de Device y accedemos a los dispositivos con un report más reciente para mirar el detalle y sus aplicaciones.
Pero en la lista de Device del portal no salen ordenados, ni hay forma de ordenarlos. 

### Describe the solution you'd like

La lista de Devices poder ordenarla superior e informente por las columnas:
"Device", "Last Report", "Policy" y "User"

Para nosotros, debería haber dos columnas diferentes en Info: una para la batería y otra para Last Report. Es mucho más util para dar un soporte sobre dispositivos, la última vez que haya habido reporte que la batería que tenga el dispositivo

![image](https://user-images.githubusercontent.com/98879063/152130476-62f0b871-1866-45e1-848e-05237fd91f41.png)

**Comment by CesarTrigo** [comment]
Gracias @JacobFLRepsol. Hemos estado analizando el requisito y ha sido planificado para el **Q2 de 2022**, junto con el 
lanzamiento de nuestro nuevo Dashboard.
Os mantendremos informados.
C.

**Comment by CesarTrigo** [comment]
Hi @JacobFLRepsol , thank you for your request. It has been implemented and deployed successfully. Please find an evidence below:
<img width="1552" alt="shorting" src="https://user-images.githubusercontent.com/453657/204768641-391144e6-7e46-4406-9a6d-5669ceab585f.png">
