### ISSUE TITLE
[Feature]: A more descriptive error message for "Couldn't process the file"

### ISSUE THREAD

**Issue by mw-mmiller** [applivery/roadmap#202]
### Is your feature request related to a problem or need? Please describe.

With the outage on July 20th, builds were erroring with the message "Couldn't process the file" and the link to the "Build processing codes" page that didn't give any additional info. It would be helpful to know if it's a backend issue or something wrong with the build specifically than just a generic error message.

### Describe the solution you'd like

A more descriptive error message

**Comment by CesarTrigo** [comment]
A more descriptive error report will be provided at build level when it can not be processed. Expected to be released in September 2022.

**Comment by CesarTrigo** [comment]
Hi @mw-mmiller, 
As mentioned [here](https://github.com/applivery/roadmap/issues/203#issuecomment-1272363843), all build processing errors have been reviewed and can be reviewed [here](https://www.applivery.com/docs/mobile-app-distribution/builds-processing-codes/). All other errors not listed there mean that there has been a server error while processing the build. En esos casos, les recomendamos contactar con el equipo de soporte a través de [email](mailto:support@applivery.com) o chat.
