### ISSUE TITLE
[Feature]: Realtime Status Page Updates

### ISSUE THREAD

**Issue by mw-mmiller** [applivery/roadmap#203]
### Is your feature request related to a problem or need? Please describe.

During the outage on July 20th, nearly all of our builds were erroring but the Applivery status page didn't reflect any issues. It would be helpful if that page was somehow integrated deeper into the backend to proactively detect/report issues.

### Describe the solution you'd like

A realtime reporting status page

**Comment by CesarTrigo** [comment]
An improved / automated reporting process is going to be placed to provide a better incident communication experience. Expected to be released during September 2022.

**Comment by CesarTrigo** [comment]
Dear @mw-mmiller 
Several improvements have been deployed these days to provide a more clear view about the service status:

1. All build error codes have been reviewed and can be checked [here](https://www.applivery.com/docs/mobile-app-distribution/builds-processing-codes/). All other errors not listed there mean that there has been a **server error** while processing the build.
2. Whenever a service incident has been reported through the [Status Page](https://status.applivery.com), a pop-up will be prompted on the Applivery dashboard to provide additional visibility.
3. On top of the Service Status  page (https://status.applivery.com) that provides a reactive status of the service where incidents and announcements are published, a new real time monitoring system has been released and can be found here: https://monitor.applivery.com/. This service will show and notify about any existing major server issue causing a disruption of the service.

Hope these two thing help you have better and instant visibility over the service status and ongoing incidents.

**Comment by mw-mmiller** [comment]
Sounds great! Thank you @CesarTrigo and team!
