### ISSUE TITLE
On click of "Install Now" shows "No Result" page

### ISSUE THREAD

**Issue by tishihara148** [applivery/roadmap#207]
I create developer and tester account.
I upload Android kotlin app apk file.
The test receive Email with "Install now" button.
After click "Install now" button, it goes to web page of "No results"

**Comment by CesarTrigo** [comment]
Hi @tishihara148 , thank you for contacting us.
Can you please share your Applivery account details (email and workspace name) with us at support@applivery.com.
Thank you,
C.

**Comment by tishihara148** [comment]
Hi,

Account email : ***@***.******@***.***>
Workspace name : Screenbeam

Thanks,
T

From: César Trigo ***@***.***>
Date: Thursday, June 22, 2023 at 11:45 PM
To: applivery/roadmap ***@***.***>
Cc: Toru Ishihara ***@***.***>, Mention ***@***.***>
Subject: Re: [applivery/roadmap] On click of "Install Now" shows "No Result" page (Issue #207)


Hi @tishihara148<https://us-west-2.protection.sophos.com?d=github.com&u=aHR0cHM6Ly9naXRodWIuY29tL3Rpc2hpaGFyYTE0OA==&i=NjBmNzA2Y2MyOGFjNjYwZjUwYWMzY2Q5&t=R3h3VURzNkdpZ0g1VXFrU0xiWDYzVTJZVGdWYUlkSlZzQzE2bS91NFVsMD0=&h=c413dc3e3870449aaba1736bc58c568e&s=AVNPUEhUT0NFTkNSWVBUSVZ-CzEl059Ym1RlqwKl3ZhNfC-dR2N5IDL9CUAdMA_6tA> , thank you for contacting us.
Can you please share your Applivery account details (email and workspace name) with us at ***@***.******@***.***>.
Thank you,
C.
