### ISSUE TITLE
Guest user role in Private App Store

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#58]
**Is your feature request related to a problem? Please describe.**
Right now there are only roles for admins and developers. In both cases these users have some type of administrative permission on the Apps or organizations.

**Describe the solution you'd like**
New type of user with read-only permissions over Apps and Organizations.

**Describe alternatives you've considered**
Use developers but they can upload and delete builds beside other permissions.

**Additional context**
Mainly focussed on quality assurance teams and/or management users that would like to follow a project evolution

**Comment by mkm12789** [comment]
+1 
A large team in our studio is blocked from being able to use Applivery due to this feature not being available.
The specific need is around granting desktop access to third party app testers who need to re-sign ipas on their end.

**Comment by CesarTrigo** [comment]
Hi @mkm12789, thank you for your patience and apologies for postponing this issue. We have reviewed this topic again and we will be implementing a new feature that will allow App Store users to download the `.ipa` or `.apk` files from the Distribution Site if the "Dev Info" option is enabled on it. It has been selected for development and you can expect a soon release (even in August). We are still considering adding a new user role "Viewer" in the Dashboard but there are not many stakeholders so far. I'll open a new FR for that specific feature and rename this one as "Guest user role in App Store"
Regards,
C.

**Comment by mkm12789** [comment]
@CesarTrigo Awesome, thank you!

Do you have a link to the ticket regarding downloading `.ipa` or `.apk` files from the Distribution Sites for our tracking purposes?

**Comment by CesarTrigo** [comment]
Hi @mkm12789, actually this is the one. The one related with the dashboard is #136 .

The team just completed the task and it's under QA. In the meantime, please let me show you an example:
<img width="357" alt="Captura de pantalla 2020-08-12 a las 0 38 55" src="https://user-images.githubusercontent.com/453657/89956125-d220da80-dc34-11ea-9f57-69ce3efc25eb.png">

We will keep you posted here.

Regards,
C.

**Comment by CesarTrigo** [comment]
Hi again @mkm12789 
The new feature has been released and it is generally available. Please remember to configure your Distribution Sites as follows:
Show History -> Enabled (optional but useful to enable the full history of builds of the App)
Show Dev Info -> Enabled (to display the download `ipa`, `apk` and `aab` buttons)
<img width="694" alt="Captura de pantalla 2020-08-13 a las 20 39 25" src="https://user-images.githubusercontent.com/453657/90173854-55f9d480-dda5-11ea-86f5-6d81840fc340.png">

**Comment by mkm12789** [comment]
Awesome @CesarTrigo!

Our team is very grateful for this feature.

We have one additional request, and if you'd like I can create a separate ticket for it. 

Our team would like a way to share those download links (either a direct link to download the build or some link to the information about the build, although I feel the former would be simpler to implement). The reason being, we want to share specific builds without having our guest users search through the private App Store to do so. The functionality exists in the dashboard for sharing a build which is why we're also interested in the other ticket (https://github.com/applivery/roadmap/issues/136#event-3643504048).
Either that feature or the 'sharing' of a build from the private App Store would solve our problem.

Thanks for all the hard work as usual!

**Comment by CesarTrigo** [comment]
Thank you again @mkm12789.
Meanwhile the Dashboard role is designed (FR #136), we are considering adding a new feature that allows creating a permalink to an specific build in the History of an App. Please give us some time to discuss it (mainly from a performance perspective due to the high number of builds some Apps have). I will open a FR once defined and mention you there for your information and tracking purposes.
