### ISSUE TITLE
Update to the Create Distribution Site API

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#75]
When Creating a Distribution Site, I'd like the option to set security to 'private' as well as assign groups. Currently the documentation says it only supports 'public' or 'password' and no option for 'groups'. Attempting the actual api call says the only valid values are 'public', 'password', or 'logged'.

`{"status":false,"error":{"code":6002,"message":"Body Validation Error","data":{"errors":[{"field":["security"],"location":"body","messages":["\"security\" must be one of [public, password, logged]"],"types":["any.allowOnly"]},{"field":["password"],"location":"body","messages":["\"password\" is required"],"types":["any.required"]}]}}}`

https://www.applivery.com/docs/rest-api/create-distribution-site/#200

**Comment by Jaimeer** [comment]
Hello, please can you share with us the curl that you are trying to execute.
Remember to DO NOT share the bearer header
Regards

**Comment by CesarTrigo** [comment]
Private **distribution sites** are identified as `logged`in the API.
Fixing documentation is coming.

Thank you for the report @mkm12789 .

C.

**Comment by CesarTrigo** [comment]
Grups assignation can be done through the `tags` filed with comma separated values. i.e.: `group1,group2`. this field will eventually be renamed to `groups` in a near future.
