### ISSUE TITLE
Search criteria

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#78]
Group permissions on a Distribution Site work in an `AND` function where only users who are a part of **ALL groups** can view the site.

Related issue: #72

**Comment by CesarTrigo** [comment]
Distribution Sites will accept a new array of arrays param called `groups`. it will accept both `AND` and `OR` logical clauses as follow:
```
"groups": [
    [
        "group1",
        "group2"
    ],
    [
        "group3"
    ]
]
```

Each array within the first level of the array will be considered as an `OR` clause. Each item within the second level will be considered as an `AND` clausule.

In the example users that belong to both `group1` AND `group2` OR just to `group3` will have access: `(group1 && group2) || (group2)`.

It's already under development

**Comment by mkm12789** [comment]
@CesarTrigo What is the estimated completion date for this feature?

**Comment by CesarTrigo** [comment]
Hi @mkm12789 
It has been released today. Additional information can be found [here](https://www.applivery.com/docs/advanced/distribution-groups/).

Have a nice weekend,
C.
