### ISSUE TITLE
App Store list of Apps instead of Distribution Sites

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#79]
Homepage is a list of all Distribution Sites the user has access to, we'd prefer a list of apps under which the sites are listed

**Comment by CesarTrigo** [comment]
Release date delayed to late next week due to an unplanned major release of the Builds Processing system.

**Comment by mkm12789** [comment]
Did this go out with the last release?

**Comment by CesarTrigo** [comment]
Dear @mkm12789 ,

It has been released during this last weekend release. Attached you'll see some screenshots that demonstrate the behaviour:
![IMG_3812](https://user-images.githubusercontent.com/453657/69664925-9b486b80-1089-11ea-8584-987485e3f78c.PNG)
![IMG_3813](https://user-images.githubusercontent.com/453657/69664926-9b486b80-1089-11ea-9039-a9448d44158c.PNG)
