### ISSUE TITLE
New User Invites Don’t Save Groups Associated with Invite

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#83]
**Describe the bug**
When inviting new users, specifically Collaborators, via the Organization's 'People' section, the Groups that are associated with the user do not get saved once the user has verified their email and been added to the organization.

**To Reproduce**
1. Go to the People section of an Organziation
2. Under the Collaborators, enter an email and add one or many groups.
3. Click "Add collaborator"
4. Have the new user set their password and verify their email
5. Notice the user does not have the groups associated with them that were set during the initial invite process.

**Expected behavior**
Group setting should persist from the invite process through the user verifying their email and being added to the organization

**Comment by CesarTrigo** [comment]
Solved and waiting for release, most probably during the 3rd week of Jan 2020.

**Comment by CesarTrigo** [comment]
Fixed and releashed! @mkm12789 please feel free to reopen the issue if you face any other issue.
Thank you for the bug report!
C.
