### ISSUE TITLE
New User Unable to Set Password if Log in with Google

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#84]
**Describe the bug**
A new user who receives an invite to Applivery is sent a link to enter their name and password. On this page they have the option to Log in with Google. If they do log in with Google, they successfully have access to the site without going through the email verification process and also without setting a password. The user has no way to set a password after this and cannot access the App Store site.

**To Reproduce**
1. Invite a Google user to Applivery
2. Have the user click the link in the email
3. Instead of entering their name and password, have them click "Log in with Google"
4. Observe they haven't set a password and have no way to set a password. They cannot access the App Store site 

**Expected behavior**
A couple suggestions:
1. Do not enable the "Log in with Google" option during the invite process when the user sets their password.
2. Allow a user to create a password in their account settings page if they do not have one.

**Comment by CesarTrigo** [comment]
Thank you @mkm12789 for the report. It will be fixed in the next Production Release, expected to be published before the end of the year.

**Comment by CesarTrigo** [comment]
As suggested by @mkm12789  I'm closing to open a new Feature Request to allow users to create or change the  password in their account settings
