### ISSUE TITLE
Localize "publicaciones/publicación" text on App Store site

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#85]
**Describe the bug**
When changing the view on the App Store site from Distribution Pages to Apps, the sub text reads "publicaciones" or "publicación" when it should be localized to "publications" or "publication"

**To Reproduce**
1. Using a browser set for English, Browse to an App Store page
2. Set view to list of Apps
3. Notice the Spanish text which should be in English

**Comment by CesarTrigo** [comment]
Thank you @mkm12789 for the report. It will be fixed in the next Production Release, expected to be published before the end of the year.
