### ISSUE TITLE
Sorting Apps/Pages

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#86]
Not sure if this is a bug or feature.

**Is your feature request related to a problem? Please describe.**
It's difficult to navigate the App Store site when the apps and sites are not sorted

**Describe the solution you'd like**
We'd like all apps and sites to be sorted by Name across the service. Here are a few specific places we've noticed:
1. Dashboard "Apps" page - currently sorted by date created, we'd like this to be by name or a feature to change the sorting
2. Dashboard "Store" page - Published apps is currently sorted by date created, we'd like this to be by name
3. App Store page - not sure how it's currently sorted, but at least for the collapsed "apps" view, we'd like this to be sorted by name
4. App Store page - when viewing the collapsed "apps" view, if you expand one of the apps to drop down the list of sites, we'd like this to be sorted by name. A bonus would be an option to customize the order of this list.

**Comment by CesarTrigo** [comment]
@mkm12789 thank you for suggesting this feature. We have classified this as a Feature or Enhancement rather than a bug :) It will require some analysis from our side, mainly for the 3rd and 4th scenarios.
1st and 2nd make absolute sense for us so they will be prioritized.

We will keep you posted here.

**Comment by mkm12789** [comment]
Thanks @CesarTrigo! Some of my teammates have been asking when we can expect this feature. I see that it's in the Q1 Milestone. Should we expect it to be in place in April or will it be done sooner?

**Comment by CesarTrigo** [comment]
Hi @mkm12789 , thank you for following up on this topic.
We will be updating all issues between today and tomorrow. In the meantime, please note that this feature will be released this week.

I'll keep you posted in the coming hours.

Best,
C.

**Comment by CesarTrigo** [comment]
In progress. Points 1 and 2 are already from the API side. We will provide support from the dashboard and Store sides during the coming 2 weeks. Expected release by 1st week of Feb.

**Comment by CesarTrigo** [comment]
Hi @mkm12789,

I just want to let you know that we have just released a new version that includes several changes regarding this issue:

- Dashboard "Apps" page is now sorted by App Name
- Dashboard "Store" page is now sorted by App Name (ascending or descending)
- App Store page is now sorted by App Name
- App Store Collapsed "apps" view is now sorted by Distribution Name

Please let me also attach some evidences:
<img width="1205" alt="apps" src="https://user-images.githubusercontent.com/453657/72707006-b6060080-3b5f-11ea-8bcf-3ff3b95bfb8a.png">
<img width="502" alt="publications" src="https://user-images.githubusercontent.com/453657/72707004-b6060080-3b5f-11ea-8a8c-cd76df762b6e.png">
<img width="361" alt="store" src="https://user-images.githubusercontent.com/453657/72707007-b69e9700-3b5f-11ea-971b-4194d2c14f04.png">

**Comment by CesarTrigo** [comment]
Hi @mkm12789,
Just as a quick update, we are enhancing this feature across the dashboard to enable users with some additional control over filtering and sorting of Apps:
<img width="1217" alt="apps-sorting" src="https://user-images.githubusercontent.com/453657/73162257-b10bf880-40ed-11ea-9b14-bc198d92b6a4.png">
