### ISSUE TITLE
When Installing IPA, Some iOS Devices Ask to "Open in iTunes"

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#88]
**Describe the bug**
My apologies for not having more details but on some iOS devices, when installing an app from the App Store, a message appears asking if you want to "Open in iTunes". If you click "Yes" the install happens normally. If you click "No", this install and future installs won't work. I'm still gathering information from my team for details on which devices it's happening on but that's all I have for now.

**Comment by RafaelFernandezAlv** [comment]
I could reproduce this issue. In my case  this happened over on iPhone Xr with iOS 12.1

![IMG_0086](https://user-images.githubusercontent.com/1234765/72961671-2efc9680-3db2-11ea-8474-6b6ac58469f1.PNG)

**Comment by CesarTrigo** [comment]
Thank you both for the report and confirmation. Unfortunately, there's no documentation at all about this issue and no accurate public documentation from Apple related to the `itms-services` that are used to launch the installation process.

After several tests, the same IPA file with the same download .`plist` manifest, under 2 different devices with the same OS version are showing different results in Safari.

Apologies but it's still under investigation.

Thank you

**Comment by CesarTrigo** [comment]
Tentatively closing the issue after Apple's confirmation that this issue is not related with our platform but with the way Apple manages IPAs under certain OS versions and also depending on the Browser (only happening in some Safari versions)
