### ISSUE TITLE
Slow Install Times

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#89]
**Describe the bug**
This has only been noticed on iOS. App installs can take upwards of 5 minutes. If I try to download the same app from my desktop, it takes just as long. It appears to be an issue of transfer speed which is, at some times, in the Kilobytes/second. Part of the problem may be that the files are hosted in eu-west in S3 and we're located in the western United States.
I recall hearing there may be an option to self-host the apps in our own S3 buckets but not sure what the timeline is on that, but that could resolve part of the problem. Is there anything else that can be done from your end to speed up transfers?

**Comment by CesarTrigo** [comment]
Hi @mkm12789 
First of all, apologies for the inconvenience and thank you for the report.
As you just mentioned, we already **partially support** the possibility of using custom S3 buckets under the organization but the feature is not fully available from the dashboard yet.

Please give us the chance to discuss the possibilities internally and come back to you.

Thank you
