### ISSUE TITLE
"Unexpected error" while creating a new feedback report (iPhone XS & XS Max)

### ISSUE THREAD

**Issue by CesarTrigo** [applivery/roadmap#91]
**Describe the bug**
An "Unexpected error" is displayed when submitting a new feedback report from an iPhone XS and XS Max. 

**To Reproduce**
1. Open Feedback report feature by taking an screenshot
2. Make sure the screenshot is attached to the report
3. Submit the report

**Expected behavior**
Feedback report closes modal view without errors and feedback report is sent.

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max & iPhone XS
 - iOS version: all

**Additional context**
Most probably it could be related with the high resolution of iPhone XS devices family since it works perfectly if the screenshot is not attached.

**Screenshots**
![unexpected-error](https://user-images.githubusercontent.com/453657/72882342-c5717f00-3d02-11ea-92c9-af9ea5b44238.png)

**Comment by CesarTrigo** [comment]
Fixed and released

**Comment by RafaelFernandezAlv** [comment]
Hi @CesarTrigo. I have the same error message again.
I use an iPhone Xs Max with iOS 13.4 and Applivery 3.1.1 library, installed with Cocoapods

**Comment by RafaelFernandezAlv** [comment]
Hi, The error was a problem with the token configuration in the app. Everything works.
Sorry!

**Comment by CesarTrigo** [comment]
Great @RafaelFernandezAlv, thank you for confirming!
C.
