### ISSUE TITLE
API - Create Distribution Site Undocumented Requirement

### ISSUE THREAD

**Issue by mkm12789** [applivery/roadmap#99]
**Describe the bug**
There seems to have been a change to the API for creating a new Distribution Site. When I use the same curl command from a few months ago I now get this error:
`{"status":false,"error":{"code":6002,"message":"Body Validation Error","data":{"errors":[{"field":["application"],"location":"body","messages":["\"application\" is required"],"types":["any.required"]}]}}}`

API Endpoint
`https://api.applivery.io/v1/integrations/distributions`

**To Reproduce**
1. Follow the documentation here to make the API call
https://www.applivery.com/docs/rest-api/create-distribution-site/

**Additional context**
I tried adding a key "application" at the top level (at the same level as slug, security, password, etc) and got this error
`{"status":false,"error":{"code":6002,"message":"Body Validation Error","data":{"errors":[{"field":["application"],"location":"body","messages":["\"application\" with value \"testappname\" fails to match the required pattern: /^[a-fA-F0-9]{24}$/"],"types":["string.regex.base"]}]}}}`

If I understand that regex properly, it will only accept names containing the letters a-f exactly 24 characters long....doesn't seem right. Perhaps it got mixed with the requirements for `token`?

**Comment by CesarTrigo** [comment]
Hi @mkm12789 , apologies for the inconvenience and thank you for the detailed report.
We are already looking into it.
We'll keep you posted
C.

**Comment by CesarTrigo** [comment]
HI @mkm12789,
There was another issue causing the incorrect return of this error.
It has been fixed and you should be able to continue using this service as usual without performing any changes.

Can you please test it out? Please, feel free to reopen the issue if you continue facing any problem.

Thank you and apologies for the inconvenience.
C.

**Comment by mkm12789** [comment]
Hi @CesarTrigo, it looks good on my end! Thank you for the quick response, I appreciate it
